### ISSUE TITLE
Create a binary release workflow

### ISSUE THREAD

**Issue by lavafroth** [TheCactusVert/mpv-sponsorblock#10]
It would be nice to have a binary release for the shared library so that a user may only have to download and place it in the right location besides the config.

I can write a github actions workflow to automate this if you are interested.

**Comment by TheCactusVert** [comment]
Hello, that would be really nice.
I don't have a lot of time to work on the project right now, so yes, if you could write a Github workflow I would be really interested !
Thanks for the help !
