### ISSUE TITLE
Keybind to toggle the script on and off?

### ISSUE THREAD

**Issue by nokia8801** [TheCactusVert/mpv-sponsorblock#14]
Once a video is loaded and the script is active, it is impossible to seek backwards to the skipped segment. A keybind toggle to turn the script on and off live would be great. Same way [mpv_sponsorblock_minimal](https://codeberg.org/jouni/mpv_sponsorblock_minimal) does it. It uses the b key, which I'm used to by now.

**Comment by TheCactusVert** [comment]
Thanks for your interest ! :) I added what you ask for, it will be in the next release but you can compile (38d4a9e825ad2703e19a5014b7161eb1341e302d) now if you want to try it.
