### ISSUE TITLE
Please publish a new release

### ISSUE THREAD

**Issue by skbeh** [TheCactusVert/mpv-sponsorblock#7]
The latest release no longer builds with latest nightly toolchain.

**Comment by TheCactusVert** [comment]
You can build the last commit for now cfc6cd3436d291d20996bd500cd20b9716912233, it doesn't require the nightly toolchain. I'm going to push a new release soon.

**Comment by TheCactusVert** [comment]
[v2.0.0-alpha.4](https://github.com/TheCactusVert/mpv-sponsorblock/releases/tag/v2.0.0-alpha.4) has been released

**Comment by skbeh** [comment]
@TheCactusVert Please also update the version in https://github.com/TheCactusVert/mpv-sponsorblock/blob/8f7c6a6bf1d7f3ded226ae7e629cad676892a790/Cargo.toml#L3C3.
