### ISSUE TITLE
Issue when fetching segments

### ISSUE THREAD

**Issue by alvv-z** [TheCactusVert/mpv-sponsorblock#8]
While testing my setup on [this video](https://www.youtube.com/watch?v=fuhE6PYnRMc), the following error is printed to the terminal:
```
[2023-07-12T21:47:12Z ERROR mpv_sponsorblock::client::worker] Failed to get segments: error decoding response body: missing field `hash` at line 1 column 675
```
I also tested this on other videos, and they gave the same error.

**Comment by TheCactusVert** [comment]
Is this problem still persisting ? It's possible that SponsorBlock might have been down during this time, you can check server status here: https://status.sponsor.ajay.app/

**Comment by alvv-z** [comment]
Yeah, it still occurs.

**Comment by TheCactusVert** [comment]
I have fixed, the problem. SponsorBlock API changed and I didn't know, thanks.
